branches:
  except:
    - /travis-.*/

install:
  ps: |
        Import-Module '.\build\appveyor-tool.ps1'
        Bootstrap
        
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
        
before_build:
  - nuget restore nunit.sln

build_script: 
  - ps: .\build\build.ps1 -Target "Appveyor"
  
artifacts:
- path: package\*.nupkg
#  - path: package\*.msi

# AppVeyor defaults to just its build number
version: '{build}'
# disable built-in tests.
test: off